# Generated by Django 6.0.2 on 2026-03-08 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_admin_email_remove_user_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='expiry_at',
            new_name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='news',
            name='duration_hours',
        ),
        migrations.RemoveField(
            model_name='news',
            name='is_active',
        ),
        migrations.AddField(
            model_name='news',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
