# Generated by Django 6.0.2 on 2026-03-08 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_expiry_at_news_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to='base.admin'),
        ),
    ]
