# Generated by Django 6.0.2 on 2026-03-08 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_news_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='admin',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='base.admin'),
        ),
    ]
