# Generated by Django 5.2.13 on 2026-06-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_complaint_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='onesignal_player_id',
        ),
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
